version: '3.3'

services:
  db:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: 'meva1'
      MYSQL_USER: 'meva'
      MYSQL_PASSWORD: 'meva'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3310:3306'
    expose:
      - 3310:3306
    volumes:
      # Data storage on host machine
      - ./mysql_data:/var/lib/mysql
      # Startup scripts
      - ./mysql_ddl:/docker-entrypoint-initdb.d

