version: '3.3'

services:
  # MySQL database
  db:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: 'meva1'
      MYSQL_USER: 'meva'
      MYSQL_PASSWORD: 'meva'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3310:3306'
    expose:
      - 3306
    volumes:
      # Data storage on host machine
      - ./mysql_data:/var/lib/mysql
      # Startup scripts
      - ./ddl:/docker-entrypoint-initdb.d
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 2s
        retries: 10

  # Runs the Python script to do the ETL
  etl:
    depends_on:
      db:
        condition: service_healthy
    build: .